Add 단발성, 선택지형 이벤트 / Modify main.py코드 / Add Storage 클래스,  item_dict.py
Sungmo-OSS-Project/txt_game_prototype pull request #30
Opened 2023-05-09 14:30 UTC by Kei-410

체력 감소용 단발성 이벤트와 선택지 테스트용 선택지형 이벤트를 추가함.
main.py의 루틴을 일부 수정(Days 카운팅 방식 수정)
maintenance.py 에서 최대 체력 회복 기능 추가

2023-05-09 14:36 UTC, Halozhan requested changes

2023-05-09 14:36 UTC, Halozhan commented on Events/fall_by_rock.py
> +        self.player.printHealth()
체력 감소하는 이벤트를 추가하네요! 확인했습니다.

2023-05-09 14:36 UTC, Halozhan commented on Events/meet_zombie.py
> +            print("다행히 좀비는 당신을 눈치채지 못했습니다.")
나중에 아이템 획득 코드를 반영해주셨으면 좋겠습니다. (피드백)

2023-05-09 14:36 UTC, Halozhan commented on event.py
> +                                Meet_zombie(player)]
나중에 폴더 전체를 가져와서 이벤트를 불러오는 방식을 합시다!

2023-05-09 14:36 UTC, Halozhan commented on main.py
> +                maintenance(player) # 정비할 수 있음
이건 너무 좋아요! 루틴이 맘에드네요!

2023-05-09 14:36 UTC, Halozhan commented on maintenance.py
> +    #인벤토리 관리 추가 예정
일단 이벤트는 여기까지 했으니 인벤토리 관리는 나중에 합시다!

2023-05-09 16:33 UTC, Halozhan approved these changes

2023-05-09 16:33 UTC, Halozhan approved these changes
인벤토리를 큰 범주에서 스토리지라는 클래스를 만들어서 넣었군요!
그리고 이벤트에서 아이템이 넣어지는 것도 확인했습니다.
승인합니다.

2023-05-10 13:45 UTC, bankingIT commented
좋습니다

2023-05-10 13:46 UTC, merged