아이템 획득 || 제거시 print 추가
Sungmo-OSS-Project/txt_game_prototype pull request #46
Opened 2023-05-16 02:46 UTC by AsanHO

2023-05-16 11:34 UTC, Halozhan requested changes

2023-05-16 11:34 UTC, Halozhan commented on Storage.py
> +        print(f"{item}을 획득했습니다.")
item의 타입은 Item 클래스 객체입니다.
객체의 주소를 그대로 출력하면 안되고
item.getName() 메소드를 통해서 아이템의 이름을 출력해야합니다.

2023-05-16 11:34 UTC, Halozhan commented on Storage.py
> +        print(f"{item}을 버렸습니다.")
여기도 위의 내용과 같습니다.

2023-05-16 11:36 UTC, Halozhan commented on Storage.py
> +        print(f"{item}을 버렸습니다.")
수정해서 다시 커밋해주세요!

2023-05-19 05:17 UTC, Halozhan approved these changes
아이템을 출력하는 메시지가 추가되었군요!
승인하겠습니다!

2023-05-21 10:06 UTC, Kei-410 approved these changes
아이템 변경사항을 매번 print 구문으로 적을 필요가 없겠네요. 승인하겠습니다

2023-05-21 10:07 UTC, merged