용우 - hp 감소 이벤트 추가
Sungmo-OSS-Project/txt_game_prototype pull request #51
Opened 2023-05-19 02:41 UTC by leeyongwooo

코드에 문제가 있으면 코멘트 부탁드립니다~

2023-05-19 05:13 UTC, Halozhan requested changes
위의 리뷰를 확인하고,
재작업해주세요!

2023-05-19 05:13 UTC, Halozhan commented on Events/trap.py
>  class Fall_by_rock(Event):
클래스의 제목을 이벤트 이름으로 바꿔주세요!

2023-05-19 05:13 UTC, Halozhan commented on event.py
> +from Events.trap import first
import에서 first라는 이베트 클래스는 지금 존재하지 않는 것으로 보입니다.
클래스의 이름으로 바꿔주세요!

2023-05-26 03:06 UTC, bankingIT approved these changes
코딩 이상 없는듯하며 진행해도 좋을거 같습니다

2023-05-26 03:09 UTC, Kei-410 approved these changes

2023-05-26 03:09 UTC, Kei-410 commented on Events/meet_people.py
> +            print("미구현") # 아이템창의 아이템들을 랜덤하게 2~3개 가져와서 선택할 수 있는 기능을 추가하고 싶습니다.
비슷한 종류의 이벤트를 여러 개 작성하여도 좋을 것 같습니다.
또한 아이템을 랜덤하게 제시하는 것이 아닌, 고정적인 아이템 리스트를  만드는 것이 좋을 것 같습니다.

2023-05-26 03:09 UTC, Kei-410 commented on Events/meet_people.py
> +            print("미구현")# 역시 아이템창에서 랜덤하게 2~3개 가져와서 보여줄수 있는 기능이 가능한가?
여기 또한 고정적으로 아이템을 제시하면 좋을 것 같습니다.

2023-05-29 07:12 UTC, Halozhan requested changes
파이썬 파일이 아닌거같아요!

2023-05-29 07:12 UTC, Halozhan commented on Events/meet_people
> +from Events.Event import Event
파이썬 파일 확장자가 맞나요?
제가 보기엔 확장자 명이 보이지 않습니다.

2023-06-02 01:55 UTC, rlgh565 approved these changes
확인했습니다

2023-06-02 02:02 UTC, Halozhan approved these changes
수정 다시 했네요!

2023-06-02 02:03 UTC, merged