Create open_chest(F).py
Sungmo-OSS-Project/txt_game_prototype pull request #98
Opened 2023-06-04 10:43 UTC by leeyongwooo

각종 이벤트 추가 예정

2023-06-04 11:55 UTC, Halozhan requested changes
open_chest(f).py에서 소괄호 ()는 불러올 수 없어요!
파일 이름을 수정해주세요! 파일을 Rename해주세요.

2023-06-04 12:06 UTC, Halozhan approved these changes
파일 이름을 수정해서 승인합니다.

2023-06-04 14:30 UTC, rlgh565 approved these changes
확인했습니다

2023-06-05 03:39 UTC, Kei-410 approved these changes
또 다른 상자를 여는 이벤트군요. 승인합니다.

2023-06-06 13:36 UTC, merged